### ISSUE TITLE
hyphen in the name

### ISSUE THREAD

**Issue by shara19** [rubenvereecken/py-vgdl#8]
I'm not sure if you are aware but its a real pain in the neck to import a module which has a hyphen in its name

https://stackoverflow.com/questions/8350853/how-to-import-module-when-module-name-has-a-dash-or-hyphen-in-it

**Comment by shara19** [comment]
Actually nevermind, I moved everything into the folder

**Comment by rubenvereecken** [comment]
I only just saw this. It's meant to be `pip install`ed, at which point you can access the module through its name `vgdl`.
